version: '3'

services:

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: 'http://localhost:${APP_PORT}'
      DB_HOST: '${DB_CONTAINER_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASS: '${DB_PASS}'
      DB_DATABASE: '${DB_NAME}'
    volumes:
      - /path/to/data:/config
    ports:
      - '${APP_PORT}:80'
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: '${DB_CONTAINER_NAME}'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
    volumes:
      - /path/to/data:/config
    restart: unless-stopped