version: '3'

services:

  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      PUID: 1000
      PGID: 1000
      APP_URL: '${HOST_URL:-http://localhost}:${APP_PORT:-6875}'
      DB_HOST: '${DB_CONTAINER_NAME:-bookstack_db}'
      DB_USER: '${DB_USER:-user}'
      DB_PASS: '${DB_PASS:-secret}'
      DB_DATABASE: '${DB_NAME:-bookstackapp}'
    volumes:
      - /path/to/data:/config
    ports:
      - '${APP_PORT:-6875}:80'
    restart: unless-stopped
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: '${DB_CONTAINER_NAME:-bookstack_db}'
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      MYSQL_DATABASE: '${DB_NAME:-bookstackapp}'
      MYSQL_USER: '${DB_USER:-user}'
      MYSQL_PASSWORD: '${DB_PASS:-secret}'
      MYSQL_ROOT_PASSWORD: '${DB_PASS:-secret}'
    volumes:
      - /path/to/data:/config
    restart: unless-stopped